export const GET_WALLET_REQUEST = "GET_WALLET_REQUEST";
export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS";
export const GET_WALLET_FAILURE = "GET_WALLET_FAILURE";

export const GET_TRANSACTIONS_REQUEST = "GET_TRANSACTIONS_REQUEST";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAILURE = "GET_TRANSACTIONS_FAILURE";

export const BUY_AIRTIME_REQUEST = "BUY_AIRTIME_REQUEST";
export const BUY_AIRTIME_SUCCESS = "BUY_AIRTIME_SUCCESS";
export const BUY_AIRTIME_FAILURE = "BUY_AIRTIME_FAILURE";

export const BUY_ELECTRICITY_REQUEST = "BUY_ELECTRICITY_REQUEST";
export const BUY_ELECTRICITY_SUCCESS = "BUY_ELECTRICITY_SUCCESS";
export const BUY_ELECTRICITY_FAILURE = "BUY_ELECTRICITY_FAILURE";
